[package]
name = "dprint-plugin-jsonc"
description = "JSONC formatter for dprint."
keywords = ["formatting", "formatter", "jsonc"]
version = "0.2.0"
authors = ["David Sherret <dsherret@gmail.com>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/dprint/dprint/tree/master/packages/rust-dprint-plugin-jsonc"
repository = "https://github.com/dprint/dprint"

[dependencies]
dprint-core = { path = "../rust-core", version = "0.15.0" }
jsonc-parser = { version = "0.5.0" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
dprint-development = { path = "../rust-development" }
debug-here = "0.2"
