// Do not edit this file! It is code generated based on dprint.schema.json

/**
 * Printing configuration.
 */
export interface Configuration {
    /**
     * Whether statements should use semi-colons.
     * @default true
     */
    semiColons?: boolean;
    /**
     * Whether to use single quotes (true) or double quotes (false).
     * @default false
     */
    singleQuotes?: boolean;
    /**
     * The style of newline.
     * @default "auto"
     */
    newLineKind?: "auto" | "crlf" | "lf" | "system";
    "ifStatement.semiColon"?: boolean;
}

/* @internal */
export interface ResolvedConfiguration {
    singleQuotes: boolean;
    newLineKind: "auto" | "crlf" | "lf";

    // semi colons
    "ifStatement.semiColon": boolean;
}
