#!/usr/bin/env -S deno run -A
import { defineMatrix, expr, job, step, workflow } from "jsr:@david/gagen@0.5.0";
import { crossImageRegistry, crossImageTag, crossImageTargets } from "./cross_image.ts";

// Builds the loongarch64 cross images (which bundle a from-source loongarch64
// build of LLVM) and pushes them to ghcr.io so that ci.ts can pull instead of
// rebuilding LLVM on every run. Only runs when the Dockerfile changes or when
// triggered manually.

const matrix = defineMatrix({
  target: crossImageTargets,
});

const buildJob = job("build", {
  name: matrix.target,
  runsOn: "ubuntu-22.04",
  // only publish from the canonical repo (forks lack ghcr write access)
  if: "github.repository == 'dprint/dprint'",
  permissions: { contents: "read", packages: "write" },
  strategy: { matrix, failFast: false },
  defaults: { run: { shell: "bash" } },
  steps: step(
    { name: "Checkout", uses: "actions/checkout@v6" },
    { uses: "docker/setup-qemu-action@v4" },
    { uses: "docker/setup-buildx-action@v4" },
    {
      name: "Login to ghcr.io",
      uses: "docker/login-action@v3",
      with: {
        registry: "ghcr.io",
        username: expr("github.actor"),
        password: expr("secrets.GITHUB_TOKEN"),
      },
    },
    {
      name: "Build and push",
      uses: "docker/build-push-action@v7",
      with: {
        file: ".github/workflows/cross-loongarch64.Dockerfile",
        push: true,
        tags: [
          `${crossImageRegistry}/dprint-cross-base-${matrix.target}:${crossImageTag}`,
          `${crossImageRegistry}/dprint-cross-base-${matrix.target}:latest`,
        ].join("\n"),
        "cache-from": `type=gha,scope=dprint-cross-base-${matrix.target}-${crossImageTag}`,
        "cache-to": `type=gha,mode=max,scope=dprint-cross-base-${matrix.target}-${crossImageTag}`,
        "build-args": `CROSS_BASE_IMAGE=ghcr.io/cross-rs/${matrix.target}:main\nTARGET=${matrix.target}`,
      },
    },
  ),
});

workflow({
  name: "Cross Images",
  on: {
    workflow_dispatch: {},
    push: {
      branches: ["main"],
      paths: [
        ".github/workflows/cross-loongarch64.Dockerfile",
        ".github/workflows/cross-loongarch64-images.generated.yml",
      ],
    },
  },
  jobs: [buildJob],
}).writeOrLint({
  filePath: new URL("./cross-loongarch64-images.generated.yml", import.meta.url),
  header: "# GENERATED BY ./cross-loongarch64-images.ts -- DO NOT DIRECTLY EDIT",
});
