#!/usr/bin/env -S deno run -A
import { expr, job, step, workflow } from "jsr:@david/gagen@0.6.0";

workflow({
  name: "cargo publish core-macros crate",
  on: { workflow_dispatch: {} },
  permissions: {},
  jobs: [
    job("rust", {
      name: "cargo publish core-macros crate",
      runsOn: "ubuntu-latest",
      timeoutMinutes: 30,
      // id-token: crates.io trusted publishing
      permissions: { contents: "read", "id-token": "write" },
      steps: step(
        { name: "Clone repository", uses: "actions/checkout@v7", with: { "persist-credentials": false } },
        { uses: "dsherret/rust-toolchain-file@v1" },
        { uses: "rust-lang/crates-io-auth-action@v1", id: "auth" },
        { name: "Cargo publish", env: { CARGO_REGISTRY_TOKEN: expr("steps.auth.outputs.token") }, run: ["cd crates/core-macros", "cargo publish"] },
      ),
    }),
  ],
}).writeOrLint({
  filePath: new URL("./publish_crate_core-macros.generated.yml", import.meta.url),
  header: "# GENERATED BY ./publish_crate_core-macros.ts -- DO NOT DIRECTLY EDIT",
});
