#!/usr/bin/env -S deno run -A
import { createWorkflow, expr, job, step } from "jsr:@david/gagen@0.3.0";

createWorkflow({
  name: "cargo publish core crate",
  on: { workflow_dispatch: {} },
  permissions: { "id-token": "write", contents: "read" },
  jobs: [
    job("rust", {
      name: "cargo publish core crate",
      runsOn: "ubuntu-latest",
      timeoutMinutes: 30,
      steps: step(
        { name: "Clone repository", uses: "actions/checkout@v6", with: { token: expr("secrets.GH_DPRINTBOT_PAT") } },
        { uses: "dsherret/rust-toolchain-file@v1" },
        { uses: "rust-lang/crates-io-auth-action@v1", id: "auth" },
        { name: "Cargo publish", env: { CARGO_REGISTRY_TOKEN: expr("steps.auth.outputs.token") }, run: ["cd crates/core", "cargo publish"] },
      ),
    }),
  ],
}).writeOrLint({
  filePath: new URL("./publish_crate_core.yml", import.meta.url),
  header: "# GENERATED BY ./publish_crate_core.generate.ts -- DO NOT DIRECTLY EDIT",
});
