#!/usr/bin/env -S deno run -A
import { createWorkflow, expr, job, step } from "jsr:@david/gagen@0.3.2";

createWorkflow({
  name: "Release",
  on: {
    workflow_dispatch: {
      inputs: {
        releaseKind: {
          description: "Kind of release",
          default: "minor",
          type: "choice",
          options: ["patch", "minor"],
          required: true,
        },
      },
    },
  },
  jobs: [
    job("rust", {
      name: "release",
      runsOn: "ubuntu-latest",
      timeoutMinutes: 30,
      steps: step(
        { name: "Clone repository", uses: "actions/checkout@v6", with: { token: expr("secrets.GH_DPRINTBOT_PAT") } },
        { uses: "denoland/setup-deno@v2" },
        { uses: "dsherret/rust-toolchain-file@v1" },
        {
          name: "Bump version and tag",
          env: {
            GITHUB_TOKEN: expr("secrets.GH_DPRINTBOT_PAT"),
            GH_WORKFLOW_ACTOR: expr("github.actor"),
          },
          run: [
            `git config user.email "${expr("github.actor")}@users.noreply.github.com"`,
            `git config user.name "${expr("github.actor")}"`,
            `deno run -A jsr:@dprint/automation@0.10.2/tasks/publish-release --${expr("github.event.inputs.releaseKind")} ./crates/dprint/Cargo.toml`,
          ],
        },
      ),
    }),
  ],
}).writeOrLint({
  filePath: new URL("./release.generated.yml", import.meta.url),
  header: "# GENERATED BY ./release.ts -- DO NOT DIRECTLY EDIT",
});
