#!/usr/bin/env -S deno run -A
import { createWorkflow, expr, job, step } from "jsr:@david/gagen@0.3.0";

const buildSteps = step(
  { name: "Checkout", uses: "actions/checkout@v6", with: { "persist-credentials": false } },
  { uses: "denoland/setup-deno@v2", with: { cache: true, "deno-version": "canary" } },
  { name: "Install dependencies", run: "(cd website && deno install)" },
  { name: "Build playground", run: "(cd website/playground && deno task build)" },
  { name: "Build website", run: "(cd website && deno task build:ci)" },
);

const deploy = step({
  name: "Deploy",
  if: "github.event_name == 'workflow_dispatch' && inputs.deploy",
  uses: "JamesIves/github-pages-deploy-action@releases/v3",
  with: {
    GITHUB_TOKEN: expr("secrets.GITHUB_TOKEN"),
    BRANCH: "gh-pages",
    FOLDER: "website/_site",
    "single-commit": true,
  },
}).dependsOn(buildSteps);

createWorkflow({
  name: "Website",
  on: {
    workflow_dispatch: {
      inputs: {
        deploy: {
          description: "Deploy to GitHub Pages",
          type: "boolean",
          default: false,
        },
      },
    },
    push: { branches: ["main"] },
    pull_request: { branches: ["main"] },
  },
  jobs: [
    job("build", {
      runsOn: "ubuntu-latest",
      steps: [buildSteps, deploy],
    }),
  ],
}).writeOrLint({
  filePath: new URL("./website.yml", import.meta.url),
  header: "# GENERATED BY ./website.generate.ts -- DO NOT DIRECTLY EDIT",
});
