#!/usr/bin/env -S deno run -A
import { artifact, expr, job, step, workflow } from "jsr:@david/gagen@0.6.0";

const isDeploy = "github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.deploy)";
const site = artifact("website", { retentionDays: 1 });

const buildJob = job("build", {
  runsOn: "ubuntu-latest",
  permissions: { contents: "read" },
  steps: step(
    { name: "Checkout", uses: "actions/checkout@v7", with: { "persist-credentials": false } },
    { uses: "denoland/setup-deno@v2", with: { cache: true, "deno-version": "canary" } },
    { name: "Install dependencies", run: "(cd website && deno install)" },
    { name: "Build playground", run: "(cd website/playground && deno task build)" },
    { name: "Test playground", run: "(cd website/playground && deno task test)" },
    { name: "Build website", run: "(cd website && deno task build:ci)" },
    site.upload({ path: "website/_site" }).if(isDeploy),
  ),
});

// Deploying is the only step that needs to write to the repo, so it runs in
// its own job and the build job (which runs for every PR) stays read-only.
const deployJob = job("deploy", {
  runsOn: "ubuntu-latest",
  needs: [buildJob],
  if: isDeploy,
  permissions: { contents: "write" },
  steps: step(
    // the deploy action needs the repo checked out to push to gh-pages
    { name: "Checkout", uses: "actions/checkout@v7", with: { "persist-credentials": false } },
    site.download({ dirPath: "website/_site" }),
    {
      name: "Deploy",
      uses: "JamesIves/github-pages-deploy-action@releases/v3",
      with: {
        GITHUB_TOKEN: expr("secrets.GITHUB_TOKEN"),
        BRANCH: "gh-pages",
        FOLDER: "website/_site",
        "single-commit": true,
      },
    },
  ),
});

workflow({
  name: "Website",
  on: {
    workflow_dispatch: {
      inputs: {
        deploy: {
          description: "Deploy to GitHub Pages",
          type: "boolean",
          default: false,
        },
      },
    },
    // deploy when the drafted release is published
    release: { types: ["published"] },
    push: { branches: ["main"] },
    pull_request: { branches: ["main"] },
  },
  permissions: {},
  jobs: [buildJob, deployJob],
}).writeOrLint({
  filePath: new URL("./website.generated.yml", import.meta.url),
  header: "# GENERATED BY ./website.ts -- DO NOT DIRECTLY EDIT",
});
